apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}